In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
# import url
# turn to soup object

URL = "https://en.wikipedia.org/wiki/List_of_Eurovision_Song_Contest_entries_(2004%E2%80%93present)"
page = requests.get(URL)

soup = BeautifulSoup(page.content , "html.parser")

In [2]:
result = soup.find(id = "mw-content-text") #table location

tables = result.find_all("table", class_ = "wikitable plainrowheaders") #iter trhough tables

# protytype:

# for i,table in enumerate(tables):
#     df=pd.read_html(str(table))
#     # convert list to dataframe
#     df=pd.DataFrame(df[0])
#     if i==1:
#         df_main = df.copy()
#     if i>1:
#         df_main = df_main.append(df)
#         df_main.head()

In [3]:
for i,table in enumerate(tables): #runs on each table
    # year of the table:
    year = [int(s) for s in table.find("a").text.split() if s.isdigit()]
    year = int("".join([str(integer) for integer in year]))
    print(year, i)

    df=pd.read_html(str(table)) #magic fuck you shler
    # convert list to dataframe
    df=pd.DataFrame(df[0])
    
    #fix placing(string->float, removed special characters):
    df["Placing"]= df["Placing"].apply(lambda x: x.split()[0]) 
    df['Placing'] = pd.to_numeric(df["Placing"], errors= 'coerce')
    df = df.sort_values("Country",ascending=True)

    df['Year'] = year#add year to the dataframe
    #table Merging into data frame
    if i==0:
        df_main = df.copy()
    if i>0:
        df_main = df_main.append(df)
    

    
    if year == 2021: break
    

  
    
    
    
df_main.head(50)

2004 0
2005 1
2006 2
2007 3
2008 4
2009 5
2010 6
2011 7
2012 8
2013 9
2014 10
2015 11
2016 12
2017 13
2018 14
2019 15
2021 16

,#,R/O SF,R/O F,Country,#.1,Artist,Song,Language,Songwriter(s),Placing,Year
12,930,13.0,9.0,Albania,1,Anjeza Shahini,"""The Image of You""",English,Edmond ZhulaliAgim Doçi,7.0,2004
5,923,6.0,NaN,Andorra,1,Marta Roure,"""Jugarem a estimar-nos""",Catalan,Jofre Bardagí,NaN,2004
23,941,NaN,2.0,Austria,41,Tie Break,"""Du bist""",German,Peter Zimmermann,21.0,2004
1,919,2.0,NaN,Belarus,1,Aleksandra and Konstantin,"""My Galileo""",English,Aleksandra KirsanovaKonstantin DrapezoAleksey ...,NaN,2004
27,945,NaN,13.0,Belgium,46,Xandee,"""1 Life""",English,Marc PaelinckDirk Paelinck,22.0,2004
20,938,21.0,12.0,Bosnia and Herzegovina,10,Deen,"""In the Disco""",English,Vesna Pisarović,9.0,2004
17,935,18.0,11.0,Croatia,12,Ivan Mikulić,"""You Are the Only One""",English,Ivan MikulićVedran OstojićDuško Gruborović,12.0,2004
13,931,14.0,21.0,Cyprus,22,Lisa Andreas,"""Stronger Every Minute""",English,Mike Connaris,5.0,2004
18,936,19.0,NaN,Denmark,33,Tomas Thordarson,"""Shame on You""",English,Ivar Lind GreinerIben Plesner,NaN,2004
16,934,17.0,NaN,Estonia,10,Neiokõsõ,"""Tii""",Võro,Priit PajusaarGlen PilvreAapo Ilves,NaN,2004
0,918,1.0,NaN,Finland,38,Jari Sillanpää,"""Takes 2 to Tango""",English,Mika ToivanenJari Sillanpää,NaN,2004
25,943,NaN,4.0,France,47,Jonatan Cerrada,"""À chaque pas""","French, Spanish","Ben ""Jammin"" RobbinsSteve BalsamoJonatan Cerrada",15.0,2004
26,944,NaN,8.0,Germany,48,Max Mutzke,"""Can't Wait Until Tonight""","English, Turkish",Stefan Raab,8.0,2004
9,927,10.0,16.0,Greece,25,Sakis Rouvas,"""Shake It""",English,Nikos TerzisNektarios Tyrakis,3.0,2004
29,947,NaN,17.0,Iceland,17,Jónsi,"""Heaven""",English,Sveinn Rúnar SigurðssonMagnús Þór Sigmundsson,19.0,2004
30,948,NaN,18.0,Ireland,38,Chris Doran,"""If My World Stopped Turning""",English,Brian McFaddenJonathan Shorten,22.0,2004
4,922,5.0,NaN,Israel,27,David D'Or,"""Leha'amin"" (להאמין)","Hebrew, English",David D'OrOfer MeiriEhud Manor,NaN,2004
3,921,4.0,NaN,Latvia,5,Fomins and Kleins,"""Dziesma par laimi""",Latvian,Guntars RačsTomass Kleins,NaN,2004
11,929,12.0,NaN,Lithuania,5,Linas and Simona,"""What's Happened to Your Love?""",English,Michalis AntoniouLinas AdomaitisCamden-MS,NaN,2004
14,932,15.0,15.0,Macedonia,4,Toše Proeski,"""Life""",English,Jovan JovanovIlija Nikolovski,14.0,2004
7,925,8.0,6.0,Malta,17,Julie and Ludwig,"""On Again... Off Again""",English,Philip VellaGerard James Borg,12.0,2004
8,926,9.0,NaN,Monaco,22,Maryon,"""Notre planète""",French,Philippe Bosco,NaN,2004
21,939,22.0,7.0,Netherlands,45,Re-Union,"""Without You""",English,Ed van OtterdijkAngeline van Otterdijk,20.0,2004
24,942,NaN,3.0,Norway,43,Knut Anders Sørum,"""High""",English,Thomas ThörnholmLars AnderssonDan Attlerud,24.0,2004
31,949,NaN,19.0,Poland,9,Blue Café,"""Love Song""","English, Spanish",Paweł Rurak-SokalTatiana Okupnik,17.0,2004
6,924,7.0,NaN,Portugal,38,Sofia Vitória,"""Foi magia""",Portuguese,Paulo Neves,NaN,2004
34,952,NaN,23.0,Romania,6,Sanda,"""I Admit""",English,George PopaIrina Gligor,18.0,2004
28,946,NaN,14.0,Russia,8,Julia Savicheva,"""Believe Me""",English,Maxim FadeevBrenda Loring,11.0,2004
19,937,20.0,5.0,Serbia and Montenegro,1,Željko Joksimović and Ad-Hoc Orchestra,"""Lane moje"" (Лане моје)",Serbian,Željko JoksimovićLeontina Vukomanović,2.0,2004
15,933,16.0,NaN,Slovenia,10,Platin,"""Stay Forever""",English,Simon GomilšekDiana Lečnik,NaN,2004
22,940,NaN,1.0,Spain,44,Ramón,"""Para llenarme de ti""",Spanish,Kike Santander,10.0,2004
35,953,NaN,24.0,Sweden,44,Lena Philipsson,"""It Hurts""",English,"Thomas ""Orup"" Eriksson",5.0,2004
2,920,3.0,NaN,Switzerland,45,Piero Esteriore and the MusicStars,"""Celebrate!""",English,Greg Manning,NaN,2004
33,951,NaN,22.0,Turkey,26,Athena,"""For Real""",English,Gökhan ÖzoğuzHakan Özoğuz,4.0,2004
10,928,11.0,10.0,Ukraine,2,Ruslana,"""Wild Dances""","English, Ukrainian",Ruslana LyzchickoOleksandr Ksenofontov,1.0,2004
32,950,NaN,20.0,United Kingdom,47,James Fox,"""Hold On to Our Love""",English,Gary MillerTim Woodcock,16.0,2004
28,982,NaN,8.0,Albania,2,Ledina Çelo,"""Tomorrow I Go""",English,Adrian HilaPandi Laço,16.0,2005
17,971,18.0,NaN,Andorra,2,Marian van de Wal,"""La mirada interior""",Catalan,Rafael Artesero HerreroDaniel AragayRafael Fer...,NaN,2005
0,954,1.0,NaN,Austria,42,Global.Kryner,"""Y así""","English, Spanish",Christof SpörkEdi Köhldorfer,NaN,2005
7,961,8.0,NaN,Belarus,2,Angelica Agurbash,"""Love Me Tonight""",English,Nikos TerzisNektarios Tyrakis,NaN,2005
10,964,11.0,NaN,Belgium,47,Nuno Resende,"""Le grand soir""",French,Alec MansionFrédéric Zeitoun,NaN,2005
37,991,NaN,21.0,Bosnia and Herzegovina,11,Feminnem,"""Call Me""",English,Andrej Babić,14.0,2005
20,974,21.0,NaN,Bulgaria,1,Kaffe,"""Lorraine""",English,Vesselin Vesselinov-EkoOrlin Pavlov,NaN,2005
19,973,20.0,18.0,Croatia,13,Boris Novković feat. Lado Members,"""Vukovi umiru sami""",Croatian,Boris NovkovićFranjo Valentić,11.0,2005
29,983,NaN,9.0,Cyprus,23,Constantinos Christoforou,"""Ela Ela""",English,Constantinos Christoforou,18.0,2005
23,977,24.0,13.0,Denmark,34,Jakob Sveistrup,"""Talking to You""",English,Jacob LaunbjergAndreas Mørck,9.0,2005
11,965,12.0,NaN,Estonia,11,Suntribe,"""Let's Get Loud""",English,Sven Lõhmus,NaN,2005
15,969,16.0,NaN,Finland,39,Geir Rönning,"""Why""",English,Mika ToivanenSteven Stewart,NaN,2005
38,992,NaN,24.0,France,48,Ortal,"""Chacun pense à soi""",French,Saad TabainetOrtal,23.0,2005
34,988,NaN,17.0,Germany,49,Gracia,"""Run & Hide""",English,David BrandesJane TempestJohn O'Flynn,24.0,2005

In [4]:
#extract how many songwriters for each song:
counter = 1 #default:1
songwriters=[]
for row in df_main['Songwriter(s)']: #big brain idea
    for i,letter in enumerate(row):
        if i>1:
            if letter.isupper() and row[i-1].islower() : counter += 1
        
    songwriters.append(counter)
    counter=1

print(songwriters)        
df_main['Number of Songwriter(s)'] = songwriters #add to dataframe
df_main

[2, 1, 1, 3, 2, 1, 3, 1, 2, 3, 2, 3, 1, 2, 2, 3, 3, 2, 3, 2, 2, 1, 2, 3, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 3, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 3, 3, 2, 4, 1, 3, 1, 2, 2, 1, 2, 1, 2, 1, 3, 3, 1, 3, 2, 2, 1, 4, 3, 2, 3, 2, 2, 2, 2, 2, 4, 3, 2, 3, 1, 1, 4, 1, 1, 1, 2, 2, 1, 3, 4, 3, 2, 2, 1, 2, 3, 3, 5, 2, 3, 3, 2, 1, 4, 2, 1, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 1, 2, 5, 3, 2, 2, 5, 2, 2, 3, 2, 2, 2, 1, 3, 1, 2, 2, 2, 2, 3, 1, 3, 2, 3, 2, 2, 1, 4, 1, 1, 1, 1, 4, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 3, 5, 1, 2, 2, 3, 2, 3, 3, 3, 2, 4, 2, 1, 2, 2, 2, 3, 1, 1, 2, 3, 2, 2, 2, 2, 1, 2, 3, 4, 2, 3, 2, 6, 3, 5, 2, 2, 1, 3, 2, 1, 1, 3, 1, 4, 2, 2, 3, 2, 3, 4, 3, 3, 1, 3, 2, 4, 3, 2, 1, 4, 2, 3, 2, 3, 3, 2, 4, 2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 1, 3, 3, 2, 3, 1, 1, 2, 3, 2, 8, 2, 4, 2, 2, 5, 1, 2, 3, 1, 2, 2, 1, 1, 1, 3, 2, 2, 4, 2, 4, 7, 3, 3, 2, 3, 2, 3, 2, 3, 1, 4, 3, 2, 2, 1, 1, 4, 2, 3, 2, 4, 2, 3, 1, 1, 1, 2, 4, 2, 4, 3, 2, 1, 2, 2, 5, 1, 1, 3, 2, 1, 1, 1, 2, 2, 8, 2, 2, 4, 2, 3, 1, 3, 1, 4, 2, 2, 1, 3, 2, 3, 3, 4, 1, 2, 2, 5, 2, 2, 2, 3, 2, 1, 2, 3, 2, 3, 4, 3, 3, 1, 3, 3, 2, 2, 1, 3, 2, 2, 2, 4, 3, 2, 2, 2, 1, 2, 3, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 3, 2, 1, 4, 2, 2, 3, 3, 3, 1, 3, 2, 2, 5, 3, 4, 3, 2, 3, 2, 2, 4, 3, 2, 2, 4, 2, 2, 4, 2, 3, 3, 3, 3, 4, 1, 1, 1, 2, 3, 1, 2, 2, 6, 1, 2, 1, 4, 5, 2, 4, 3, 3, 1, 2, 2, 3, 2, 3, 5, 4, 3, 2, 1, 2, 2, 1, 1, 3, 2, 4, 4, 3, 4, 2, 1, 2, 1, 2, 3, 2, 3, 3, 2, 1, 2, 1, 7, 5, 2, 2, 3, 3, 3, 1, 2, 1, 4, 2, 2, 3, 4, 4, 2, 4, 2, 2, 3, 6, 3, 5, 3, 2, 3, 1, 2, 1, 3, 1, 5, 1, 2, 2, 5, 4, 2, 4, 3, 2, 4, 2, 1, 3, 3, 4, 4, 2, 3, 3, 4, 3, 2, 2, 1, 3, 5, 6, 1, 4, 3, 1, 2, 2, 2, 3, 3, 1, 4, 2, 2, 4, 3, 3, 4, 3, 5, 2, 2, 3, 3, 1, 2, 3, 4, 1, 2, 3, 3, 4, 3, 1, 3, 3, 5, 2, 2, 3, 4, 2, 5, 1, 2, 4, 4, 2, 3, 4, 4, 5, 1, 3, 2, 3, 1, 1, 2, 4, 2, 1, 3, 1, 4, 1, 3, 3, 5, 4, 3, 2, 4, 3, 2, 3, 1, 2, 3, 1, 6, 3, 2, 3, 6, 3, 3, 5, 2, 3, 2, 4, 4, 2, 3, 3, 2, 3, 3, 3, 4, 4, 2, 4, 5, 6, 4, 1, 3, 3, 2, 2, 2, 1, 3, 5, 4, 2, 2, 3, 4, 2, 4, 3, 4, 2, 1, 2, 5, 3, 1, 2, 3, 1, 4, 4, 4, 3, 6, 4, 4, 2, 3, 3, 4, 1, 2, 3, 10, 3, 4, 4, 4, 4, 2, 5]

,#,R/O SF,R/O F,Country,#.1,Artist,Song,Language,Songwriter(s),Placing,Year,Number of Songwriter(s)
12,930,13.0,9.0,Albania,1,Anjeza Shahini,"""The Image of You""",English,Edmond ZhulaliAgim Doçi,7.0,2004,2
5,923,6.0,NaN,Andorra,1,Marta Roure,"""Jugarem a estimar-nos""",Catalan,Jofre Bardagí,NaN,2004,1
23,941,NaN,2.0,Austria,41,Tie Break,"""Du bist""",German,Peter Zimmermann,21.0,2004,1
1,919,2.0,NaN,Belarus,1,Aleksandra and Konstantin,"""My Galileo""",English,Aleksandra KirsanovaKonstantin DrapezoAleksey ...,NaN,2004,3
27,945,NaN,13.0,Belgium,46,Xandee,"""1 Life""",English,Marc PaelinckDirk Paelinck,22.0,2004,2
...,...,...,...,...,...,...,...,...,...,...,...,...
34,1599,NaN,13.0,Spain,60,Blas Cantó,"""Voy a quedarme""",Spanish,Blas CantóLeroy SanchezDangelo OrtegaDan Hammond,24.0,2021,4
3,1568,4 *,25.0,Sweden,60,Tusse,"""Voices""",English,"Joy DebLinnea DebJimmy ""Joker"" ThörnfeldtAnder...",14.0,2021,4
31,1596,16 **,11.0,Switzerland,61,Gjon's Tears,"""Tout l'univers""",French,Gjon MuharremajWouter HardyNina SampermansXavi...,3.0,2021,4
14,1579,15 *,19.0,Ukraine,16,Go_A,"""Shum"" (Шум)",Ukrainian,Taras ShevchenkoKateryna Pavlenko,5.0,2021,2
33,1598,NaN,9.0,United Kingdom,63,James Newman,"""Embers""",English,James NewmanConor BlakeDanny ShahTom HollingsS...,26.0,2021,5

In [5]:
#extract how many languages for each song:
counter = 1 #default :1
languages=[]
for row in df_main['Language']:  #another big brain idea
    for letter in  row:
        if letter ==',' : counter += 1
        
    languages.append(counter)
    counter=1

print(languages)        
df_main['Number of Languages'] = languages #add to data frame
df_main

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 4, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 6, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1]

,#,R/O SF,R/O F,Country,#.1,Artist,Song,Language,Songwriter(s),Placing,Year,Number of Songwriter(s),Number of Languages
12,930,13.0,9.0,Albania,1,Anjeza Shahini,"""The Image of You""",English,Edmond ZhulaliAgim Doçi,7.0,2004,2,1
5,923,6.0,NaN,Andorra,1,Marta Roure,"""Jugarem a estimar-nos""",Catalan,Jofre Bardagí,NaN,2004,1,1
23,941,NaN,2.0,Austria,41,Tie Break,"""Du bist""",German,Peter Zimmermann,21.0,2004,1,1
1,919,2.0,NaN,Belarus,1,Aleksandra and Konstantin,"""My Galileo""",English,Aleksandra KirsanovaKonstantin DrapezoAleksey ...,NaN,2004,3,1
27,945,NaN,13.0,Belgium,46,Xandee,"""1 Life""",English,Marc PaelinckDirk Paelinck,22.0,2004,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,1599,NaN,13.0,Spain,60,Blas Cantó,"""Voy a quedarme""",Spanish,Blas CantóLeroy SanchezDangelo OrtegaDan Hammond,24.0,2021,4,1
3,1568,4 *,25.0,Sweden,60,Tusse,"""Voices""",English,"Joy DebLinnea DebJimmy ""Joker"" ThörnfeldtAnder...",14.0,2021,4,1
31,1596,16 **,11.0,Switzerland,61,Gjon's Tears,"""Tout l'univers""",French,Gjon MuharremajWouter HardyNina SampermansXavi...,3.0,2021,4,1
14,1579,15 *,19.0,Ukraine,16,Go_A,"""Shum"" (Шум)",Ukrainian,Taras ShevchenkoKateryna Pavlenko,5.0,2021,2,1
33,1598,NaN,9.0,United Kingdom,63,James Newman,"""Embers""",English,James NewmanConor BlakeDanny ShahTom HollingsS...,26.0,2021,5,1

In [6]:
#fix SF column
df_main["R/O SF"]= df_main["R/O SF"].apply(lambda x: x.split()[0] if type(x) == str else x) 
df_main['R/O SF'] = pd.to_numeric(df_main["R/O SF"], errors= 'coerce')
df_main

,#,R/O SF,R/O F,Country,#.1,Artist,Song,Language,Songwriter(s),Placing,Year,Number of Songwriter(s),Number of Languages
12,930,13.0,9.0,Albania,1,Anjeza Shahini,"""The Image of You""",English,Edmond ZhulaliAgim Doçi,7.0,2004,2,1
5,923,6.0,NaN,Andorra,1,Marta Roure,"""Jugarem a estimar-nos""",Catalan,Jofre Bardagí,NaN,2004,1,1
23,941,NaN,2.0,Austria,41,Tie Break,"""Du bist""",German,Peter Zimmermann,21.0,2004,1,1
1,919,2.0,NaN,Belarus,1,Aleksandra and Konstantin,"""My Galileo""",English,Aleksandra KirsanovaKonstantin DrapezoAleksey ...,NaN,2004,3,1
27,945,NaN,13.0,Belgium,46,Xandee,"""1 Life""",English,Marc PaelinckDirk Paelinck,22.0,2004,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,1599,NaN,13.0,Spain,60,Blas Cantó,"""Voy a quedarme""",Spanish,Blas CantóLeroy SanchezDangelo OrtegaDan Hammond,24.0,2021,4,1
3,1568,4.0,25.0,Sweden,60,Tusse,"""Voices""",English,"Joy DebLinnea DebJimmy ""Joker"" ThörnfeldtAnder...",14.0,2021,4,1
31,1596,16.0,11.0,Switzerland,61,Gjon's Tears,"""Tout l'univers""",French,Gjon MuharremajWouter HardyNina SampermansXavi...,3.0,2021,4,1
14,1579,15.0,19.0,Ukraine,16,Go_A,"""Shum"" (Шум)",Ukrainian,Taras ShevchenkoKateryna Pavlenko,5.0,2021,2,1
33,1598,NaN,9.0,United Kingdom,63,James Newman,"""Embers""",English,James NewmanConor BlakeDanny ShahTom HollingsS...,26.0,2021,5,1

In [7]:
#using only relevant columns
final_df = df_main[["R/O SF",'R/O F','Placing', 'Language', 'Songwriter(s)', 'Number of Languages','Number of Songwriter(s)', 'Year']].copy()
final_df

,R/O SF,R/O F,Placing,Language,Songwriter(s),Number of Languages,Number of Songwriter(s),Year
12,13.0,9.0,7.0,English,Edmond ZhulaliAgim Doçi,1,2,2004
5,6.0,NaN,NaN,Catalan,Jofre Bardagí,1,1,2004
23,NaN,2.0,21.0,German,Peter Zimmermann,1,1,2004
1,2.0,NaN,NaN,English,Aleksandra KirsanovaKonstantin DrapezoAleksey ...,1,3,2004
27,NaN,13.0,22.0,English,Marc PaelinckDirk Paelinck,1,2,2004
...,...,...,...,...,...,...,...,...
34,NaN,13.0,24.0,Spanish,Blas CantóLeroy SanchezDangelo OrtegaDan Hammond,1,4,2021
3,4.0,25.0,14.0,English,"Joy DebLinnea DebJimmy ""Joker"" ThörnfeldtAnder...",1,4,2021
31,16.0,11.0,3.0,French,Gjon MuharremajWouter HardyNina SampermansXavi...,1,4,2021
14,15.0,19.0,5.0,Ukrainian,Taras ShevchenkoKateryna Pavlenko,1,2,2021
33,NaN,9.0,26.0,English,James NewmanConor BlakeDanny ShahTom HollingsS...,1,5,2021

In [8]:
#Bool, Song in English? 1:0
english=[]
for row in final_df["Language"]:
    # print(row, type(row))
    if 'English' in row : english.append(1)
    else : english.append(0)

print(english, len(english))

final_df["English"] = english

final_df

[1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1] 686

,R/O SF,R/O F,Placing,Language,Songwriter(s),Number of Languages,Number of Songwriter(s),Year,English
12,13.0,9.0,7.0,English,Edmond ZhulaliAgim Doçi,1,2,2004,1
5,6.0,NaN,NaN,Catalan,Jofre Bardagí,1,1,2004,0
23,NaN,2.0,21.0,German,Peter Zimmermann,1,1,2004,0
1,2.0,NaN,NaN,English,Aleksandra KirsanovaKonstantin DrapezoAleksey ...,1,3,2004,1
27,NaN,13.0,22.0,English,Marc PaelinckDirk Paelinck,1,2,2004,1
...,...,...,...,...,...,...,...,...,...
34,NaN,13.0,24.0,Spanish,Blas CantóLeroy SanchezDangelo OrtegaDan Hammond,1,4,2021,0
3,4.0,25.0,14.0,English,"Joy DebLinnea DebJimmy ""Joker"" ThörnfeldtAnder...",1,4,2021,1
31,16.0,11.0,3.0,French,Gjon MuharremajWouter HardyNina SampermansXavi...,1,4,2021,0
14,15.0,19.0,5.0,Ukrainian,Taras ShevchenkoKateryna Pavlenko,1,2,2021,0
33,NaN,9.0,26.0,English,James NewmanConor BlakeDanny ShahTom HollingsS...,1,5,2021,1

In [9]:
#export Df to CSV file
final_df.to_csv('2004.csv',index=False)